# requirements.yaml
dependencies:
- name: binderhub
  version: 0.2.0-n219.hbc17443
  repository: https://jupyterhub.github.io/helm-chart/
  import-values:
    - child: rbac
      parent: rbac
- name: nginx-ingress
  version: 1.34.2
  repository: https://kubernetes-charts.storage.googleapis.com
- name: dask-gateway
  version: "0.9.0"
  repository: 'https://dask.org/dask-gateway-helm-repo/'
