# requirements.yaml
dependencies:
- name: binderhub
  version: 0.2.0-n219.hbc17443
  repository: https://jupyterhub.github.io/helm-chart/
  import-values:
    - child: rbac
      parent: rbac
- name: nginx-ingress
  version: 1.34.2
  repository: https://kubernetes-charts.storage.googleapis.com
- name: dask-gateway
  version: "0.8.0"
  repository: 'https://dask.org/dask-gateway-helm-repo/'
- name: prometheus
  version: 11.16.2
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus.enabled
- name: grafana
  version: 5.8.10
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled
