projectName: pangeo-binder-aws-staging

binderhub:
  config:
    BinderHub:
      build_node_selector:
        hub.jupyter.org/node-purpose: user
      hub_url: https://hub.staging.aws-uswest2-binder.pangeo.io
      badge_base_url: https://staging.aws-uswest2-binder.pangeo.io
      image_prefix: pangeoaccess/binder-staging-
      use_registry: true
  nodeSelector:
    hub.jupyter.org/node-purpose: core
  resources:
    requests:
      cpu: 50m
      memory: 100Mi

  ingress:
    enabled: true
    hosts:
      - staging.aws-uswest2-binder.pangeo.io
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/issuer: letsencrypt-production
      https:
        enabled: true
        type: nginx
    tls:
      - secretName: staging-aws-uswest2-binder-pangeo-io-tls
        hosts:
          - staging.aws-uswest2-binder.pangeo.io

  dind:
    enabled: true
    hostLibDir: /var/lib/dind/stage
    hostSocketDir: /var/run/dind/stage

  jupyterhub:
    proxy:
      nodeSelector:
        hub.jupyter.org/node-purpose: core
      chp:
        resources:
          requests:
            cpu: 50m
            memory: 100Mi

      nginx:
        resources:
          requests:
            cpu: 50m
            memory: 100Mi

    ingress:
      enabled: true
      hosts:
        - hub.staging.aws-uswest2-binder.pangeo.io
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/issuer: letsencrypt-production
        https:
          enabled: true
          type: nginx
      tls:
         - secretName: hub-staging-aws-uswest2-binder-pangeo-io-tls
           hosts:
            - hub.staging.aws-uswest2-binder.pangeo.io

    singleuser:
      serviceAccountName: pangeo
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://hub.staging.aws-uswest2-binder.pangeo.io/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-staging-dask-gateway.staging:80"

    hub:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi

      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: http://traefik-staging-dask-gateway.staging

prometheus:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 0m
      memory: 0Gi
grafana:
  resources:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 0m
      memory: 0Gi
  ingress:
    enabled: true
    path: /grafana/?(.*)
    hosts:
      - staging.aws-uswest2-binder.pangeo.io
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: "true"
