controller:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hub.jupyter.org/node-purpose
            operator: In
            values:
            - core

  resources:
    limits:
      cpu: 500m
      memory: 4Gi
    requests:
      cpu: 0m
      memory: 0Gi


